export const LOGIN_USER= "LOGIN_USER"
export const REGISTER_USER= "REGISTER_USER"
export const LOG_OUT= "LOG_OUT"

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const LOAD_USER= "LOAD_USER"  
export const FAIL_USER= "FAIL_USER"  

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';



